import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";

import NavBar from "../components/navBar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		// always the height is 100%
		<html  lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-full min-h-screen flex flex-col overflow-x-hidden`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
					{/* fixed we git rid of the flow and its always on top */}
					<div className=" fixed top-0 right-0 left-0 z-50 ">
						<NavBar />
					</div>
					{/* take all the space that is left */}
					{/* navbar has height at 12 so we do a margin-top 12 so it has some space and doesnt overlapse */}
					<div className=" flex flex-1 flex-col min-h-0 z-10 pt-12">
						{children}
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
